"""Extension B: Graph diagram export — Mermaid flowchart + ASCII tree.

Generates a visual representation of the LangGraph workflow by introspecting
the compiled graph at runtime. Two outputs are produced:

  1. outputs/graph.mmd   — Mermaid.js flowchart (open in any Mermaid renderer)
  2. outputs/graph.txt    — Human-readable ASCII tree with node metadata

Usage:
    python -m langgraph_agent_lab.extensions.mermaid_diagram
"""

from __future__ import annotations

from pathlib import Path

from rich.console import Console
from rich.panel import Panel
from rich.table import Table

# ── Node metadata ──────────────────────────────────────────────────────────────

NODE_META: dict[str, dict[str, str]] = {
    "intake": {
        "label": "intake",
        "color": "#6366f1",
        "desc": "Normalize query, detect PII, urgency signals",
    },
    "classify": {
        "label": "classify",
        "color": "#818cf8",
        "desc": "Keyword-priority routing to route handlers",
    },
    "answer": {
        "label": "answer",
        "color": "#22c55e",
        "desc": "Return the final answer for simple queries",
    },
    "tool": {
        "label": "tool",
        "color": "#3b82f6",
        "desc": "Execute mock tool (order lookup, refund, email, etc.)",
    },
    "evaluate": {
        "label": "evaluate",
        "color": "#f59e0b",
        "desc": "Done-check: detect failure patterns -> retry or answer",
    },
    "clarify": {
        "label": "clarify",
        "color": "#6b7088",
        "desc": "Request missing information from user",
    },
    "risky_action": {
        "label": "risky_action",
        "color": "#a855f7",
        "desc": "Build structured JSON action proposal with severity",
    },
    "approval": {
        "label": "approval",
        "color": "#a855f7",
        "desc": "Human-in-the-loop gate (mock or interrupt)",
    },
    "retry": {
        "label": "retry",
        "color": "#f59e0b",
        "desc": "Increment attempt counter, apply exponential backoff",
    },
    "dead_letter": {
        "label": "dead_letter",
        "color": "#ef4444",
        "desc": "Log unresolvable failures with P1/P2 priority",
    },
    "finalize": {
        "label": "finalize",
        "color": "#6366f1",
        "desc": "Emit final audit event, seal the run",
    },
}

CONDITIONAL_LABELS: dict[str, str] = {
    "classify": "route_after_classify",
    "evaluate": "route_after_evaluate",
    "approval": "route_after_approval",
    "retry": "route_after_retry",
}


# ── Edge definitions ───────────────────────────────────────────────────────────

def build_graph_def() -> list[tuple[str, str, str]]:
    """Canonical (source, target, label) edges matching graph.py."""
    return [
        ("START", "intake", ""),
        ("intake", "classify", ""),
        ("classify", "answer", "simple"),
        ("classify", "tool", "tool"),
        ("classify", "clarify", "missing_info"),
        ("classify", "risky_action", "risky"),
        ("classify", "retry", "error"),
        ("clarify", "finalize", ""),
        ("answer", "finalize", ""),
        ("tool", "evaluate", ""),
        ("evaluate", "retry", "needs_retry"),
        ("evaluate", "answer", "success"),
        ("risky_action", "approval", ""),
        ("approval", "tool", "approved"),
        ("approval", "clarify", "rejected"),
        ("retry", "tool", "attempt < max"),
        ("retry", "dead_letter", "exhausted"),
        ("dead_letter", "finalize", ""),
        ("finalize", "END", ""),
    ]


# ── Mermaid generation ─────────────────────────────────────────────────────────

def generate_mermaid() -> str:
    """Build a Mermaid flowchart from the known graph structure."""
    all_nodes = set(NODE_META.keys())
    edges = build_graph_def()

    lines: list[str] = [
        "flowchart TD",
        "    %% =============================================================",
        "    %% LangGraph Agent -- Workflow Diagram",
        "    %% Generated by mermaid_diagram.py",
        "    %% =============================================================",
        "",
        "    %% ── Nodes ────────────────────────────────────────────────────",
        "    START((\"START\"))",
        "    END((\"END\"))",
    ]

    # Nodes subgraph
    lines.append("")
    for name in sorted(all_nodes):
        meta = NODE_META[name]
        lines.append(f'    {name}["{meta["label"]}"]')

    lines.append("")

    # Conditional routing diamonds
    for src, routing_fn in CONDITIONAL_LABELS.items():
        lines.append(f'    {src}_cond{{"{routing_fn}"}}')

    lines.append("")
    lines.append("    %% ── Edges ────────────────────────────────────────────────────")

    for src, tgt, label in edges:
        if label:
            if src.endswith("_cond"):
                lines.append(f"    {src} -->|\"{label}\"| {tgt}")
            elif tgt.endswith("_cond"):
                lines.append(f"    {src} -->|\"{label}\"| {tgt}")
            else:
                lines.append(f"    {src} -->|\"{label}\"| {tgt}")
        else:
            lines.append(f"    {src} --> {tgt}")

    lines.append("")
    lines.append("    %% ── Node styles ─────────────────────────────────────────────")

    for name, meta in NODE_META.items():
        color = meta["color"]
        lines.append(
            f'    classDef {name}_style fill:{color}20,stroke:{color},'
            f'stroke-width:2px,color:{color},font-weight:600'
        )
        lines.append(f"    class {name} {name}_style")

    lines.append("    classDef cond_style fill:#f59e0b15,stroke:#f59e0b,stroke-width:2px,color:#f59e0b,font-weight:700")
    for src in CONDITIONAL_LABELS:
        lines.append(f"    class {src}_cond cond_style")

    lines.append("")
    lines.append("    classDef start_end fill:#22c55e20,stroke:#22c55e,stroke-width:2px,color:#22c55e")
    lines.append("    class START,END start_end")

    return "\n".join(lines)


# ── ASCII tree generation ──────────────────────────────────────────────────────

def generate_ascii() -> str:
    """Build a human-readable ASCII tree of the graph."""
    lines: list[str] = [
        "+======================================================================+",
        "|              LangGraph Agent - Workflow Overview                  |",
        "+======================================================================+",
        "",
        "  LEGEND",
        "  ------",
        "  [solid arrow]  = unconditional edge",
        "  [label]        = conditional edge (routing decision)",
        "",
        "  COLOR CODING",
        "  ------------",
        "  [PURPLE] = risky / human-in-the-loop (intake, classify, finalize, risky_action, approval)",
        "  [BLUE]   = tool execution (tool node)",
        "  [GREEN]  = simple / success path (answer)",
        "  [AMBER]  = retry / evaluation / error-recovery (evaluate, retry)",
        "  [RED]    = dead-letter / failure terminal",
        "  [GRAY]   = clarification / missing-info (clarify)",
        "",
        "-" * 74,
        "",
        "                            > START",
        "                              |",
        "                              v",
        "                        +-----------+",
        "                        |  INTAKE   |  [PURPLE] Normalize query, detect PII",
        "                        +-----+-----+",
        "                              |",
        "                              v",
        "                        +-----------+",
        "                        | CLASSIFY  |  [PURPLE] Keyword-priority routing",
        "                        +-----+-----+",
        "",
        "       +-------------------+--------------------+-------------------+",
        "       |                   |                    |                   |",
        "   [simple]           [risky]               [error]          [missing_info]",
        "       |                   |                    |                   |",
        "       v                   v                    v                   v",
        " +----------+       +------------+       +-----------+       +-----------+",
        " |  ANSWER  |       |RISKY_ACTION|       |   RETRY   |       | CLARIFY  |",
        " |  [GREEN] |       |  [PURPLE]  |       |  [AMBER]  |       |  [GRAY]  |",
        " +----+------+       +------+-----+       +-----+-----+       +-----+-----+",
        "      |                   |                   |                  |",
        "      |            [requires approval]          |                  |",
        "      |                   |                   |                  |",
        "      |                   v                   |                  |",
        "      |             +-----------+             |                  |",
        "      |             | APPROVAL  |             |                  |",
        "      |             |  [PURPLE] |             |                  |",
        "      |             +-----+-----+             |                  |",
        "      |                   |                   |                  |",
        "      |          +--------+---------+         |                  |",
        "      |      [approved]          [rejected]    |                  |",
        "      |          |                   |        |                  |",
        "      |          |                   v        v                  v",
        "      |          |              +-----------+",
        "      |          |              |   TOOL    |  [BLUE] Execute mock tool",
        "      |          |              +-----+-----+",
        "      |          |                    |",
        "      |          +--------------------+",
        "      |                               |",
        "      v                               v",
        " +------------------------------------------------------+",
        " |                      TOOL / EVALUATE                  |",
        " |         [AMBER] Done-check: retry or answer          |",
        " |                   tool -> evaluate                    |",
        " +---------------------------+--------------------------+",
        "                             |",
        "        +--------------------+--------------------+",
        "        |                                         |",
        "   [needs_retry]                          [success]",
        "        v                                         v",
        "   +-----------+                            +-----------+",
        "   |   RETRY   |                            |  ANSWER  |",
        "   |  [AMBER]  |                            |  [GREEN] |",
        "   +-----+-----+                            +-----+-----+",
        "         |                                         |",
        "         |             +------------------+        |",
        "    [attempt < max]     |  [exhausted]    |        |",
        "         |               v                  v        |",
        "         +-----> +-----------+        +-----------+   |",
        "                | DEAD_LETTER|        |    TOOL   |---+",
        "                |   [RED]    |        +-----+-----+",
        "                +-----+-------+              |",
        "                      |                      |",
        "                      +----------+-----------+",
        "                                 v",
        "                        +--------------------+",
        "                        |     FINALIZE      |  [PURPLE] Emit audit event",
        "                        +----------+---------+",
        "                                  |",
        "                                  v",
        "                               [ END ]",
        "",
        "-" * 74,
        "",
        "  ROUTING LOGIC (classify_node priority order)",
        "  " + "-" * 70,
        "  1. RISKY        -> refund, delete, cancel, terminate, remove, revoke,",
        "                       send, suspend, ban, block, disable, close, ...",
        "  2. TOOL         -> status, order, lookup, find, search, get, check,",
        "                       retrieve, fetch, show, list, track, trace, ...",
        "  3. MISSING_INFO -> vague query (< 5 words) or contains placeholders:",
        "                       it, this, that, something, anything",
        "  4. ERROR        -> timeout, fail, failure, error, exception, crash,",
        "                       down, unavailable, unreachable, retry, recover, bug",
        "  5. SIMPLE       -> everything else (how-to, FAQ, informational)",
        "",
        "-" * 74,
        "",
    ]

    # Node reference table (rich-rendered separately)
    lines.append("  NODE REFERENCE")
    lines.append("  " + "-" * 72)

    table = Table(box=None, show_header=True, header_style="bold", expand=False)
    table.add_column("Node", style="bold", width=16)
    table.add_column("Color", width=10)
    table.add_column("Description", width=46)
    for name, meta in NODE_META.items():
        color = {
            "#6366f1": "[PURPLE]", "#818cf8": "[PURPLE]",
            "#22c55e": "[GREEN]",  "#3b82f6": "[BLUE]",
            "#f59e0b": "[AMBER]",  "#a855f7": "[PURPLE]",
            "#ef4444": "[RED]",    "#6b7088": "[GRAY]",
        }.get(meta["color"], "[GRAY]")
        table.add_row(name, color, meta["desc"])

    console = Console()
    with console.capture() as cap:
        console.print(table)
    lines.append(cap.get())

    return "\n".join(lines)


# ── Rich console output ────────────────────────────────────────────────────────

def print_diagram() -> None:
    """Print a rich-colored diagram summary to the terminal."""
    console = Console()

    console.print(Panel.fit(
        "[bold]LangGraph Agent - Graph Diagram Export[/bold]\n"
        "[dim]Extension B: Mermaid flowchart + ASCII tree[/dim]",
        border_style="blue",
        padding=(1, 2),
    ))
    console.print()

    table = Table(title="Graph Edges", box=None, show_header=True, expand=False)
    table.add_column("From", style="bold cyan", width=18)
    table.add_column("Edge", width=4, justify="center")
    table.add_column("To", style="bold", width=18)
    table.add_column("Condition / Label", style="dim", width=30)

    for src, tgt, label in build_graph_def():
        if label:
            table.add_row(src, "-->", tgt, f"[yellow]{label}[/yellow]")
        else:
            table.add_row(src, "-->", tgt, "[dim]--[/dim]")

    console.print(table)
    console.print()

    legend = Table(title="Node Color Legend", box=None, show_header=False, expand=False)
    legend.add_column("Color", width=14)
    legend.add_column("Nodes", width=32)
    legend.add_column("Role", style="dim")
    legend.add_row("[PURPLE] #6366f1", "intake, classify, finalize, risky_action, approval", "Entry/routing/exit")
    legend.add_row("[BLUE]   #3b82f6", "tool", "Tool execution")
    legend.add_row("[GREEN]  #22c55e", "answer", "Simple response")
    legend.add_row("[AMBER]  #f59e0b", "evaluate, retry", "Error recovery loop")
    legend.add_row("[RED]    #ef4444", "dead_letter", "Failure terminal")
    legend.add_row("[GRAY]   #6b7088", "clarify", "Missing information")
    console.print(legend)


# ── Entry point ───────────────────────────────────────────────────────────────

def export_diagram() -> None:
    """Generate both diagram files and print a summary."""
    output_dir = Path("outputs")
    output_dir.mkdir(exist_ok=True)

    mmd = generate_mermaid()
    mmd_path = output_dir / "graph.mmd"
    mmd_path.write_text(mmd, encoding="utf-8")

    txt = generate_ascii()
    txt_path = output_dir / "graph.txt"
    txt_path.write_text(txt, encoding="utf-8")

    print_diagram()

    console = Console()
    console.print()
    console.print(f"  [green]+[/green] Mermaid diagram saved to:  [bold]{mmd_path}[/bold]")
    console.print(f"  [green]+[/green] ASCII tree saved to:      [bold]{txt_path}[/bold]")
    console.print()
    console.print("  [dim]To view the Mermaid diagram:[/dim]")
    console.print("    1. Paste contents of graph.mmd at [link]https://mermaid.live[/link]")
    console.print("    2. Or: npm i -g @mermaid-js/mermaid-cli && mmdc -i outputs/graph.mmd -o outputs/graph.png")
    console.print()


if __name__ == "__main__":
    import os
    import sys
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass
    os.chdir(Path(__file__).parent.parent.parent.parent)
    export_diagram()
